version: 2.1
orbs:
    aws-ecr: circleci/aws-ecr@6.7.0
workflows:
    build_and_push_image:
        jobs:
            - aws-ecr/build-and-push-image:
                  region: AWS_ECR_REGION
                  account-url: AWS_ECR_ACCOUNT_URL
                  repo: MyDealz-Scraper
                  tag: latest
                  filters:
                      branches:
                          only:
                              - main